// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNote struct {
	Text        string `json:"text"`
	Description string `json:"description"`
}

type Note struct {
	ID          string `json:"id"`
	Text        string `json:"text"`
	Description string `json:"description"`
}
